# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 20:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_posture', models.CharField(choices=[('STATUS_STARTED', 'Sitting'), ('STATUS_ENDED', 'Standing')], max_length=100)),
                ('typing_modality', models.CharField(choices=[('INDEX_FINGER', 'Index Finger'), ('THUMB', 'Thumb')], max_length=100)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='trail',
            name='user',
        ),
        migrations.DeleteModel(
            name='Trail',
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([('user', 'date')]),
        ),
    ]
