# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sensordata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touchevent',
            old_name='rect_id',
            new_name='grid_id',
        ),
        migrations.RenameField(
            model_name='touchevent',
            old_name='event_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='touchevent',
            name='x',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='touchevent',
            name='y',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
