# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170608_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='touchevent',
            name='is_hit',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
