# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_touchevent_is_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='mood',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='body_posture',
            field=models.CharField(choices=[('SITTING', 'Sitting'), ('STANDING', 'Standing')], max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='typing_modality',
            field=models.CharField(choices=[('INDEX', 'Index Finger'), ('THUMB', 'Thumb')], max_length=100),
        ),
    ]
