# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170613_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='session_code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='session_code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='touchevent',
            name='session_code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
