# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170620_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='device_model',
            field=models.CharField(default='iPhone 100', max_length=100),
            preserve_default=False,
        ),
    ]
