# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_touchevent_grid_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='device_UDID',
        ),
        migrations.RemoveField(
            model_name='touchevent',
            name='device_UDID',
        ),
        migrations.AddField(
            model_name='session',
            name='device_udid',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='hand',
            field=models.CharField(choices=[('HAND_LEFT', 'Left Hand'), ('HAND_RIGHT', 'Right Hand')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
