# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 11:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_pretestsurvey'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_mode', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='body_posture',
            field=models.CharField(choices=[('SITTING', 'Sitting'), ('STANDING', 'Standing'), ('LYING', 'Lying')], max_length=100),
        ),
    ]
