# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170801_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='lab_mode',
            field=models.BooleanField(default=False),
        ),
    ]
