# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_session_lab_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=200)),
                ('hand', models.CharField(max_length=100)),
            ],
        ),
    ]
