# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_finalsurvey'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreTestSurvey',
            new_name='Survey',
        ),
        migrations.DeleteModel(
            name='FinalSurvey',
        ),
    ]
